export class Character {
    constructor(
        public id: string,
        public characterName: string,
        public playerName: string,
        public characterClass: string,
        public level: number,
        public race: string,
        public background: {
            backgroundName: string,
            personalityTraits: string,
            ideals: string,
            bonds: string,
            flaws: string
        },
        public alignment: string,
        public experiencePoints: number,
        public inspiration: number,
        public proficiencyBonus: number,
        public stats: {
            strength: number,
            dexterity: number,
            constitution: number,
            intelligence: number,
            wisdom: number,
            charisma: number,

        },
        public savingThrows: {
            Strength: number,
            Dexterity: number,
            Constitution: number,
            Intelligence: number,
            Wisdom: number,
            Charisma: number
        },
        public skills: {
            acrobatics: number,
            animalHandling: number,
            arcana: number,
            athletics: number,
            deception: number,
            history: number,
            insight: number,
            intimidation: number,
            investigation: number,
            medicine: number,
            nature: number,
            perception: number,
            performance: number,
            persuasion: number,
            religion: number,
            sleightOfHand: number,
            stealth: number,
            survival: number,
        },
        public passivePerception: number,
        public armorClass: number,
        public initiative: number,
        public speed: number,
        public hitPointMax: number,
        public currentHitPoints: number,
        public temporaryHitPoints: number,
        public hitDice: string,
        public attacks: [],
        public spellCasting: [],
        public inventory: [],
        public otherProficienciesAndLanguages: string,
        public featuresAndTraits: string,
        public optionalCharacterDetails: {
            characterName: string,
            age: number,
            height: string,
            weight: string,
            eyeColor: string,
            skinColor: string,
            hairColor: string,
            appearanceUrl: string,
            backgroundStory: string,
            alliesAndOrganizations: string,
            symbolUrl: string,
            additionalFeaturesAndTraits: string,
            treasure: string
        }
    ){ }
}